### ISSUE TITLE
Problems with entries..

### ISSUE THREAD

**Issue by ad48hp** [SeitaroShinagawa/FavoritePapers#2]
The 'Disentangling Style and Content in Anime Illustrations' already has code available..
https://github.com/stormraiser/adversarial-disentangle
Also, the very last video in the 'One-Shot Generalization in Deep Generative Models' paper has broken link..

**Comment by SeitaroShinagawa** [comment]
Thanks for kindly showing me this info.  
I added the code. 3349312e7933a301f4b306620a1da729a4663d6c 
and removed the broken link 92e4ea4c101bec753f5bef9e14b5f2853e070aa3

Thanks,
