### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by zchenry** [SeitaroShinagawa/FavoritePapers#3]
Thank you so much for the collection!
Links below in 'summary/how_to_make_progress.md' are broken.

### 論文の読み方
- 情報系の研究者が研究・論文執筆をする際に知らなくてはならない事や心構え
- 関連研究の調べ方

### 論文の書き方
- 論文の書き方（執筆先行型）
- Wallwalk. English for Writing Research Papers (pdf) ](Phrase list, writing tips, first draft, revise)

### プレゼンの仕方
- センス不要！伝わる研究ポスター作成術

**Comment by SeitaroShinagawa** [comment]
@zchenry Thank you for your kind comments! I have fixed them. Sorry for the late reply.
